def fn(*args, x, y, **kwargs):
    print(x)
    print(y)
    print(args)
    print(kwargs)
# fn(3,5)
# fn(3,5,7)
# fn(3,5,a=1,b='python')
fn(7,9,y=5,x=3,a=1,b='python')
print("____")
fn(x=1,y='python',*(3,4))
fn(x=1,y='python',*[3,4])
fn(x=1,y='python',*{3,4})
fn(y='python',x=1,**{})